<?php

namespace App\Facade\Support\Sms;

use App\Repository\Contracts\SmsInterface;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class Unifonic implements SmsInterface
{
    public static function messages($code): string
    {
        return match ($code) {
            200     => 'Success',
            400     => 'No Rules Matched',
            401     => 'Authentication failed',
            402     => 'Missing parameter AppSid',
            404     => 'Incompatible API version',
            406     => 'Wrong parameter format',
            409     => 'This message is duplicate',
            410     => 'Invalid recipient format',
            412     => 'Message body is too long',
            415     => 'Invalid hex string',
            417     => 'Wrong body format',
            419     => 'Wrong date format in request',
            420     => 'Page limit Exceeds',
            421     => 'No message body specified',
            422     => 'No recipient parameter specified',
            423     => 'Required timeScheduled parameter is not passed',
            429     => 'Too many requests generated by this user',
            431     => 'MessageId is empty',
            432     => 'MessageId must be numeric',
            440     => 'Wrong sender format',
            449     => 'Message body is empty',
            450     => 'Too many destination numbers provided',
            451     => 'TimeScheduled parameter must indicate time in the future',
            452     => 'User must specify either messageId or recipient parameter',
            455     => 'Scheduled message not found for this User',
            456     => 'Wrong correlationId format',
            459     => 'Authentication parameters are incorrectly base64 encoded',
            460     => 'Invalid encoding (Should be UCS2 or GSM7)',
            480     => 'This user cannot use specified SenderID',
            481     => 'Country does not exist',
            482     => 'Invalid dest num',
            483     => 'Operator is not found',
            499     => 'Error in configuration request',
            546     => 'Incompatible external data type in configuration',
            548     => 'Wrong dictionary configuration for response parameter',
            599     => 'Request failed',
            default => 'Unknown Error !.',
        };
    }

    public static function data($number, $message): array
    {
        return [
            'AppSid'         => config('sms.sms_password'),
            'SenderID'       => config('sms.sms_sender_name'),
            'Recipient'      => $number,
            'Body'           => $message,
            'responseType'   => 'JSON',
            'CorrelationID'  => '%22%22',
            'baseEncode'     => 'true',
            'statusCallback' => 'sent',
            'async'          => 'false',
        ];
    }

    public static function send($number, $message): array
    {
        $result = Http::post('https://el.cloud.unifonic.com/rest/SMS/messages', self::data($number, $message))->object();

        $code = $result->errorCode;

        if ($code != 'ER-00') Log::warning('Unifonic SMS : ' . $result->message . ' for mobile number => ' . $number);

        return ['code' => $code, 'message' => self::messages($code)];
    }
}
